# Generated by Django 6.0.2 on 2026-02-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=20, verbose_name='Логин'),
            preserve_default=False,
        ),
    ]
