# Generated by Django 6.0.2 on 2026-02-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('fio', models.CharField(max_length=100, verbose_name='Фамилия Имя Отчество')),
                ('comments', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
