# Generated by Django 6.0.2 on 2026-02-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('can_view_all_clients', 'Can view all clients')]},
        ),
    ]
