# Generated by Django 6.0.2 on 2026-02-19 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mail_messages', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_view_all_messages', 'Can view all messages')]},
        ),
    ]
