# Generated by Django 6.0.2 on 2026-02-19 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_disable_mailing', 'Can disable mailing'),
                                     ('can_view_all_clients', 'Can view all clients')]},
        ),
    ]
