# Generated by Django 6.0.2 on 2026-02-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_disable_mailing', 'Can disable mailing'), ('can_view_all_mailings', 'Can view all mailings')]},
        ),
    ]
